<text2Screen>:
    BoxLayout:
        orientation: "vertical"

        Button:
            text: 'We hope we can help you today.'
            on_press: 
                root.manager.transition.direction = 'left'
                root.manager.current = 'text3Screen'

        Button:
            text: 'Back'
            on_press:
                root.manager.transition.direction = 'right'
                root.manager.current = 'text1Screen'